### PR TITLE
update jest ts-jest

### PR DESCRIPTION
**Pull request by alphmth**
**Please check if the PR fulfills these requirements**
- [x] Followed the [Contributing](https://github.com/jaredwray/airhorn/blob/main/CONTRIBUTING.md) guidelines.
- [x] Tests for the changes have been added (for bug fixes/features) with 100% code coverage.
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
upgraded jest, ts-jest

### CODE REVIEW

**Comment by alphmth** [comment]
@jaredwray the FIREBASE_CERT & TWILLO_SENDGRIP_API_KEY are not defined, that is why tests are failing

**Comment by jaredwray** [comment]
> @jaredwray the FIREBASE_CERT & TWILLO_SENDGRIP_API_KEY are not defined, that is why tests are failing

@alphmth - this was working before did something change in the code to not take in the environment variables?

**Comment by alphmth** [comment]
@jaredwray no.. There is only a change in package.json. Tests run locally fine.

**Comment by jaredwray** [comment]
@alphmth - it looks like something changed. Maybe with Jest where the environment variables are not being passed. 

I just did a pull request using the same build.yml file and it worked: https://github.com/jaredwray/airhorn/pull/157

**Comment by alphmth** [comment]
Can you approve 2 workflows?

**Comment by alphmth** [comment]
@jaredwray are these under environment secrets section? 

https://github.com/prisma/prisma/issues/10204#issuecomment-974017838

**Comment by alphmth** [comment]
@jaredwray please approve workflow

**Comment by jaredwray** [comment]
> prisma/prisma#10204 (comment)

Yep. they are under the repo section and work.

**Comment by alphmth** [comment]
@jaredwray The github secrets are not passed to runner when a workflow is triggered from for repo https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow

But this can solve our problem: 

https://dev.to/petrsvihlik/using-environment-protection-rules-to-secure-secrets-when-building-external-forks-with-pullrequesttarget-hci

**Comment by jaredwray** [comment]
Ah I see.

What would be better is to remove the requirement for these two keys and to mock the tests. Can you set that up?
________________________________

**Comment by alphmth** [comment]
@jaredwray ok I will set mocks

**Comment by jaredwray** [comment]
@alphmth - looks like no tests have ran. 

Also, what is `this.json`?

**Comment by alphmth** [comment]
@jaredwray `this.json` is just dummy filename

**Pull request merged**
